# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)

# NOTE: This crate is OPTIONAL.  Only needed when the `mbedtls` feature is
# enabled on cda-comm-doip.  See comm-mbedtls/mbedtls-sys/BUILD.bazel for
# instructions on enabling mbedtls support.
#
# load("@cda_crates//:defs.bzl", "aliases", "all_crate_deps")
# load("@rules_rust//rust:defs.bzl", "rust_library")
#
# rust_library(
#     name = "mbedtls-rs",
#     srcs  = glob(["src/**/*.rs"]),
#     edition = "2024",
#     crate_name = "mbedtls_rs",
#     visibility = ["//visibility:public"],
#     deps = [
#         "//comm-mbedtls/mbedtls-sys:mbedtls-sys",
#         "@cda_crates//:libc",
#     ],
# )

exports_files(["Cargo.toml"])
